additional_footer_content:
  default: ''
# The instance name
app_title:
  default: HeyDay
app_subtitle:
  default: Make Your Day Smart
welcome_text:
  default:
attachment_max_size:
  format: int
  default: 5120
mail_from:
  default: openproject@example.net
bcc_recipients:
  default: 1
plain_text_mail:
  default: 0
text_formatting:
  default: textile
cache_formatted_text:
  default: 0
per_page_options:
  default: '10, 25, 50, 100'
available_languages:
  serialized: true
  default:
  - en
default_language:
  default: en
date_format:
  default: ''
time_format:
  default: ''
user_format:
  default: :firstname_lastname
  format: symbol
ui_theme:
  default: 'gsem'
user_may_override_theme:
  default: 1
emails_footer:
  serialized: true
  default:
    en: |-
      You have received this notification because you have either subscribed to it, or are involved in it.
      To change your notification preferences, please click here: http://hostname/my/account
gravatar_enabled:
  default: 0
default_notification_option:
  default: 'only_my_events'
emails_header:
  serialized: true
  default:
    en: ''
start_of_week:
  default: ''
